### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by Skyvassa** [baibhavkumarpoudel/project3-backend#1]
1) What is the process for Config File creation, with username and password.
2) Nothing, but don't want to cause an issue.

**Comment by davidmagbee** [comment]
Please be sure to _try something_ **before** submitting an issue ticket. We are going to continue to let go and allow you to be empowered as developers to find your answers given the resources, skills, and training you've received thus far. Do not forget about all of the lesson repositories and videos you have access to from throughout the cohort. 

This [Sequelize Intro](https://git.generalassemb.ly/cfg-seir-2/sequelize-intro) will _surely_ be helpful in understanding the `config.js` file.

**Comment by davidmagbee** [comment]
Please be sure to `close` your issue ticket if you've resolved your issues. @Skyvassa @baibhavkumarpoudel
