### ISSUE TITLE
bcrypt error

### ISSUE THREAD

**Issue by baibhavkumarpoudel** [baibhavkumarpoudel/project3-backend#3]
![image](https://user-images.githubusercontent.com/82845499/122254992-50708d80-ce93-11eb-9d70-15db957facb8.png)
![image](https://user-images.githubusercontent.com/82845499/122255025-56ff0500-ce93-11eb-8ef2-620684011f07.png)

1. we came across another error regarding bcrypt. It seems it is a dependency that's needed in order for our code to work
2. tried looking at articles on the internet but not sure if we should install this or use another method... We have multiple .js dependencies questions like these that we would love clarifications on

**Comment by davidmagbee** [comment]
Discussed in breakout room. `closed`
