### ISSUE TITLE
Backend Pulls

### ISSUE THREAD

**Issue by Skyvassa** [baibhavkumarpoudel/project3-backend#4]
Backend is presenting issues with my pulls, specifically in regards to it not pulling the full backend project despite the changes processed.
Do not want to touch for fear of danger to the project itself, and not familiar with how to pull old code in the case of a total wipe.
![image](https://user-images.githubusercontent.com/82845166/122278747-3cd61e80-ceb5-11eb-9e35-bebaf530550f.png)

**Comment by davidmagbee** [comment]
What resources have you reviewed to dig into this error? There are a number of possible causes.

**Comment by CRHarding** [comment]
Are you doing the git pull via vscode or via git bash?

**Comment by Skyvassa** [comment]
The only resources I can find online describe not being given permission, which is definitely not the case. I was using VSCODE for that attempt, GitBash was not cooperating due to guardian issues. Reattempted on Gitbash again, and that seems to have pulled all code. I'd say issue resolved for the moment.

**Comment by CRHarding** [comment]
Here's what I got when I looked it up: https://stackoverflow.com/questions/19180612/fatal-cannot-create-directory-at-root-wp-content-cache-page-enhanced-no-such

The main culprit seemed to be that some other process was locking the files which didn't allow git to modify them.

**Comment by davidmagbee** [comment]
I found that same resource... here's everything for that rabbit hole. 😉

[Google search of the issue](https://www.google.com/search?q=fatal%3A+cannot+create+directory&oq=fatal%3A+cannot+create+directory+&aqs=chrome..69i57j69i58.11795j0j4&sourceid=chrome&ie=UTF-8)
[git checkout issue](https://stackoverflow.com/questions/39650678/git-checkout-error-cannot-create-directory-permission-denied)
[fatal: cannot create directory at /root/wp-content/cache/page_enhanced/ No such a file or directory](https://stackoverflow.com/questions/19180612/fatal-cannot-create-directory-at-root-wp-content-cache-page-enhanced-no-such)
[git checkout error: unable to create file](https://stackoverflow.com/questions/14811991/git-checkout-error-unable-to-create-file)
[Filename too long git](https://www.codegrepper.com/code-examples/shell/git+fatal%3A+cannot+create+directory+at+%3A+Filename+too+long)

**Comment by davidmagbee** [comment]
@Skyvassa Be sure to close this issue ticket once you've resolved the issue.
